# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('volume', models.FloatField()),
                ('weight', models.FloatField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
