# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 10:42
from __future__ import unicode_literals

from django.db import migrations


def fill_in_vehicles(apps, schema_editor):
    Vehicle = apps.get_model("vehicles", "Vehicle")

    Vehicle.objects.create(volume=9, weight=1.5, type='Газель фургон')
    Vehicle.objects.create(volume=9, weight=1.5, type='Газель грузопассажирская')
    Vehicle.objects.create(volume=17, weight=3, type='Бычок тент-фургон')
    Vehicle.objects.create(volume=22, weight=3, type='Бычок тент-фургон')
    Vehicle.objects.create(volume=22, weight=5, type='Фургон гидролифт')
    Vehicle.objects.create(volume=34, weight=10, type='Тент')
    Vehicle.objects.create(volume=82, weight=20, type='Фура')


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_in_vehicles),
    ]
