# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 07:52
from __future__ import unicode_literals

from django.db import migrations


def fill_in_cities(apps, schema_editor):
    Location = apps.get_model("locations", "Location")

    Location.objects.create(city='KYIV')


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_in_cities),
    ]
