# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170218_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
