# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170222_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cost',
            field=models.IntegerField(null=True),
        ),
    ]
